name: "Deploy Godot to GitHub Pages"
on:
  push:
    branches: [ main ] # 如果你的主分支叫 master，请改为 master

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Godot Export
        uses: firebelley/godot-export@v5.2.1
        with:
          godot_executable_download_url: https://godot-releases.nbg1.your-objectstorage.com/4.5.1-stable/Godot_v4.5.1-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://godot-releases.nbg1.your-objectstorage.com/4.5.1-stable/Godot_v4.5.1-stable_export_templates.tpz
          relative_project_path: ./
          archive_export_output: false
          # 必须匹配你 preset.2 的名字
          export_preset_name: Web
          
      - name: Patch for GitHub Pages (SharedArrayBuffer)
        run: |
          # 1. 进入你配置的导出目录 web/
          cd web
          
          # 2. 下载补丁脚本
          wget https://raw.githubusercontent.com/gzuidhof/coi-serviceworker/master/coi-serviceworker.js
          
          # 3. 在 index.html 的 <script> 标签前插入引用
          # 这一行会在生成的 HTML 中加入 <script src="coi-serviceworker.js"></script>
          sed -i 's|<script|<script src="coi-serviceworker.js"></script><script|' index.html

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # 注意：根据你的配置，Godot 会把文件放在 web/ 目录下
          folder: web
          branch: gh-pages