name: "Deploy Godot to GitHub Pages"
on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      # 关键步骤：在云端临时关闭 Android 和 Windows 预设的激活状态
      # 这样 Godot 就不会因为找不到 Android SDK 而报错了
      - name: Disable other presets for CI
        run: |
          sed -i '/name="Android"/,/runnable=true/s/runnable=true/runnable=false/' export_presets.cfg
          sed -i '/name="Windows Desktop"/,/runnable=true/s/runnable=true/runnable=false/' export_presets.cfg

      - name: Godot Export
        uses: firebelley/godot-export@v5.2.1
        with:
          godot_executable_download_url: https://godot-releases.nbg1.your-objectstorage.com/4.5.1-stable/Godot_v4.5.1-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://downloads.godotengine.org/?version=4.5.1&flavor=stable&slug=export_templates.tpz&platform=templates
          relative_project_path: ./
          archive_export_output: false
          export_preset_name: Web

      - name: Patch for GitHub Pages (SharedArrayBuffer)
        run: |
          cd web
          wget https://raw.githubusercontent.com/gzuidhof/coi-serviceworker/master/coi-serviceworker.js
          sed -i 's|<script|<script src="coi-serviceworker.js"></script><script|' index.html

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: web
          branch: gh-pages